#!/bin/bash

kickass g9k-test.asm

HOST=192.168.1.5
USER=deadline
PASSWORD=pw
ftp -inv $HOST <<EOF
user $USER $PASSWORD
cd Usb1/github/HACKME/Gladiator9000/commodore64/prg_files
delete g9k-test.d64
lcd prg_files
binary
put g9k-test.d64
delete g9k-test.prg
bye
EOF


